import Layout from '@/pages/layout/Layout';
import {
  AdminCityManage,AdminCityManageStaff,
  AdminMessageService,AdminBigScreenService,AdminPublicService,AdminParkPublicService,AdminProgramService
} from 'parkingos-ui';

export const adminOtherRouter = {
  path:'/',
  name:'adminOtherRouter',
  component:Layout,
  children:[
    {
      path:'/city_manage_staff',
      name:'city_manage_staff',
      title:'厂商员工',
      component:AdminCityManageStaff
    },
  ]
}

export const adminRouter = [
  {
    path:'/',
    name:'city_manage',
    icon:'el-icon-tickets',
    title:'厂商管理',
    meta:{
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/city_manage',
        title:'厂商管理',
        name:'city_manage',
        meta:{
          hidden:false,
        },
        component:AdminCityManage
      },
    ]
  },
  {
    path:'/',
    name:'',
    icon:'el-icon-star-off',
    title:'增值服务',
    meta:{
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/message_service',
        title:'短信服务',
        name:'message_service',
        meta:{
          hidden:false,
        },
        component:AdminMessageService
      },
      {
        path:'/bigScreen_service',
        title:'大屏服务',
        name:'bigScreen_service',
        meta:{
          hidden:false,
        },
        component:AdminBigScreenService
      },
      {
        path:'/public_service',
        title:'商户公众号',
        name:'public_service',
        meta:{
          hidden:false,
        },
        component:AdminPublicService
      },
      {
        path:'/parkpublic_service',
        title:'车场公众号',
        name:'parkpublic_service',
        meta:{
          hidden:false,
        },
        component:AdminParkPublicService
      },
      {
        path:'/program_service',
        title:'小程序收费',
        name:'program_service',
        meta:{
          hidden:false,
        },
        component:AdminProgramService
      },
    ]
  },
]
