import Layout from '@/pages/layout/Layout';
import secondLevelLayout from '@/pages/layout/secondLevelLayout';

import {
  MyAccount,SerManage,SerManageStaff,UnionManage,UnionManageStaff,
  ParkManage,ParkManageStaff,MaterialTemplatePage,MaterielTable,
  MoneyRecord,NewUnionProfit,RoleManage,EmployeeManage,MessageNtification,
  SettingManage,AuthManage,SystemMangeLog,Development
} from 'parkingos-ui';


export const cityOtherRouter = {
  path:'/',
  name:'cityOtherRouter',
  component:Layout,
  children:[
    {
      path:'/ser_manage_staff',
      name:'ser_manage_staff',
      title:'服务商员工',
      component:SerManageStaff
    },
    {
      path:'/union_manage_staff',
      name:'union_manage_staff',
      title:'运营集团员工',
      component:UnionManageStaff
    },
    {
      path:'/park_manage_staff',
      name:'park_manage_staff',
      title:'车场员工',
      component:ParkManageStaff
    },
    {
      path:'/cityParkManage_parkManagePage/materialTemplate',
      name:'materialTemplate',
      title:'车场二维码',
      component:MaterialTemplatePage
    },
  ]
};

export const cityRouter = [
  {
  path:'/',
  name:'my_account',
  icon:'el-icon-news',
  title:'我的账户',
  onlyOne:true,
  meta:{
    authority:'city_account',
    hidden:false,
  },
  component:Layout,
  children:[
    {
      path:'/city_account',
      title:'我的账户',
      name:'city_account',
      meta:{
        hidden:false,
      },
      component:MyAccount
    },
  ]
},{
  path:'/',
  name:'citySerManage',
  icon:'el-icon-menu',
  title:'工程服务商',
  onlyOne:true,
  meta:{
    authority:'citySerManage',
    hidden:false,
  },
  component:Layout,
  children:[
    {
      path:'/serManagePage',
      title:'服务商管理',
      name:'serManagePage',
      meta:{
        authority:'citySerManage_serManagePage',
        hidden:false,
      },
      component:SerManage
    },
  ]
},{
    path:'/',
    name:'cityUnionManage',
    icon:'el-icon-menu',
    title:'运营集团',
    onlyOne:true,
    meta:{
      authority:'cityUnionManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/unionManagePage',
        title:'运营集团管理',
        name:'unionManagePage',
        meta:{
          authority:'cityUnionManage_unionManagePage',
          hidden:false,
        },
        component:UnionManage
      },
    ]
  },{
    path:'/',
    name:'cityParkManage',
    icon:'el-icon-menu',
    title:'车场管理',
    meta:{
      authority:'cityParkManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/cityParkManage_parkManagePage',
        title:'车场管理',
        name:'cityParkManage_parkManagePage',
        meta:{
          authority:'cityParkManage_parkManagePage',
          hidden:false,
        },
        component:ParkManage
      },
      {
        path:'/cityParkManage_materielPage',
        title:'物料管理',
        name:'cityParkManage_materielPage',
        meta:{
          authority:'cityParkManage_materielPage',
          hidden:false,
        },
        component:MaterielTable
      },
    ]
  },{
    path:'/',
    name:'cityTrade',
    icon:'el-icon-document',
    title:'交易中心',
    onlyOne:true,
    meta:{
      authority:'cityTrade',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/cityTrade_MoneyRecord',
        title:'资金流水',
        name:'cityTrade_MoneyRecord',
        meta:{
          hidden:false,
        },
        component:MoneyRecord
      },
    ]
  },{
    path:'/',
    name:'cityStatistics',
    icon:'el-icon-document',
    title:'统计分析',
    onlyOne:true,
    meta:{
      authority:'cityStatistics',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/cityStatistics_NewUnionProfit',
        title:'车场分润报表',
        name:'cityStatistics_NewUnionProfit',
        meta:{
          hidden:false,
        },
        component:NewUnionProfit
      },
    ]
  },{
    path:'/',
    name:'cityResources',
    icon:'iconfont icon-yuangongguanli',
    title:'人力资源',
    meta:{
      authority:'cityResources',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/cityResources_RoleManage',
        title:'角色管理',
        name:'cityResources_RoleManage',
        meta:{
          authority:'cityResources_RoleManage',
          hidden:false,
        },
        component:RoleManage
      },{
        path:'/cityResources_EmployeeManage',
        title:'员工管理',
        name:'cityResources_EmployeeManage',
        meta:{
          authority:'cityResources_EmployeeManage',
          hidden:false,
        },
        component:EmployeeManage
      },{
        path:'/cityResources_MessageNtification',
        title:'消息通知',
        name:'cityResources_MessageNtification',
        meta:{
          authority:'cityResources_MessageNtification',
          hidden:false,
        },
        component:MessageNtification
      },
    ]
  },{
    path:'/',
    name:'citySettingManage',
    icon:'el-icon-setting',
    title:'个性化设置',
    meta:{
      authority:'citySettingManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/citySettingManage_settingPage',
        title:'个性化设置',
        name:'citySettingManage_settingPage',
        meta:{
          authority:'citySettingManage_settingPage',
          hidden:false,
        },
        component:SettingManage
      },{
        path:'/citySettingManage_authPage',
        title:'权限设置',
        name:'citySettingManage_authPage',
        meta:{
          authority:'citySettingManage_authPage',
          hidden:false,
        },
        component:AuthManage
      },
    ]
  },{
    path:'/',
    name:'city_systemMange',
    icon:'el-icon-tickets',
    title:'系统日志',
    onlyOne:true,
    meta:{
      authority:'city_systemMange',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/city_systemMange',
        title:'系统日志',
        name:'city_systemMange',
        meta:{
          hidden:false,
        },
        component:SystemMangeLog
      }
    ]
  },{
    path:'/',
    name:'development',
    icon:'el-icon-edit',
    title:'开发配置',
    onlyOne:true,
    meta:{
      authority:'development',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/development',
        title:'开发配置',
        name:'sub_development',
        meta:{
          hidden:false,
        },
        component:Development
      }
    ]
  },]
