import Layout from '@/pages/layout/Layout';
import secondLevelLayout from '@/pages/layout/secondLevelLayout'
import {
  DataCenterPark, RemoteOpening,
  OrderManageOrders, OrderManageOrderDetail, OrderManagePoles, OrderManageIncome, OrderManageExpense, OrderManageAbnormal, OrderManageRecord,
  MemberManageMonthVIP, MemberManageRefill, MemberManagePrepayCard, MemberManageRechargeRecord, MemberManageUseRecord, MemberManageWhiteList,
  VistorManage,OwnerManage,
  OrderStatisticsTollCollector,OrderStatisticsDailyReport,OrderStatisticsMonthReport,OrderStatisticsCommute,
  shopManageShop,shopManageShopStaff,shopManageQueryAccount,shopManageCoupon,shopManageShopAnalysis,
  shopManageShopClassB,shopManageShopStaffClassB,shopManageQueryAccountClassB,shopManageCouponClassB,ShopManageCouponSetClassB,
  ParkRoleManage,ParkEmployeeManage,
  ValueAddedSMS,ValueAddedDataScreen,ValueAddedSubscription,ValueAddedApplet,ValueAddedParkSubscription,
  EquipmentManageWatchhouse,EquipmentManageMonitor,EquipmentManageChannel,
  SystemManageAdvanceSet,SystemManageParkPublic,SystemManageBlackList,SystemManageAccount,SystemManageFreeReason,
  SystemManageCarType,SystemManagePrice,SystemManageMonthCard,SystemManageLogs,MonitorApp
} from 'parkingos-ui';


export const parkOtherRouter = {
  path:'/',
  name:'parkOtherRouter',
  component:Layout,
  children:[
    {
      path:'/orderManage_OrderDetail',
      name:'orderManage_OrderDetail',
      title:'订单详情',
      component:OrderManageOrderDetail
    },
    {
      path:'/ShopManage_Coupon_Staff',
      name:'ShopManage_Coupon_Staff',
      title:'商户员工',
      component:shopManageShopStaff
    },
    {
      path:'/ShopManage_Coupon_Staff_B',
      name:'ShopManage_Coupon_Staff_B',
      title:'商户员工',
      component:shopManageShopStaffClassB
    },
  ]
};

export const parkRouter = [{
  path:'/',
  name:'dataCenter',
  icon:'iconfont icon-shujuzhongxin',
  title:'数据中心',
  meta:{
    authority:'dataCenter',
    hidden:false,
  },
  component:Layout,
  children:[
    {
      path:'/dataCenter_Park',
      title:'数据中心',
      name:'dataCenter_Park',
      meta:{
        parentName:'dataCenter',
        authority:'dataCenter_Park',
        hidden:false,
      },
      component:DataCenterPark
    },
    {
      path:'/dataCenter_RemoteOpening',
      title:'车道监控',
      name:'dataCenter_RemoteOpening',
      meta:{
        parentName:'dataCenter',
        authority:'dataCenter_RemoteOpening',
        hidden:false,
      },
      component:RemoteOpening
    },
  ]
},{
  path:'/',
  name:'orderManage',
  icon:'iconfont icon-dingdanguanli',
  title:'订单管理',
  meta:{
    authority:'orderManage',
    hidden:false,
  },
  component:Layout,
  children:[
    {
      path:'/orderManage_Orders',
      title:'订单记录',
      name:'orderManage_Orders',
      meta:{
        parentName:'orderManage',
        authority:'orderManage_Orders',
        hidden:false,
      },
      component:OrderManageOrders
    },
    {
      path:'/orderManage_Poles',
      title:'抬杆记录',
      name:'orderManage_Poles',
      meta:{
        parentName:'orderManage',
        authority:'orderManage_Poles',
        hidden:false,
      },
      component:OrderManagePoles
    },
    {
      path:'/orderManage_Income',
      title:'交易记录',
      name:'orderManage_Income',
      meta:{
        parentName:'orderManage',
        authority:'orderManage_Income',
        hidden:false,
      },
      component:OrderManageIncome
    },
    {
      path:'/orderManage_Expense',
      title:'支出记录',
      name:'orderManage_Expense',
      meta:{
        parentName:'orderManage',
        authority:'orderManage_Expense',
        hidden:false,
      },
      component:OrderManageExpense
    },
    {
      path:'/orderManage_Abnormal',
      title:'异常订单',
      name:'orderManage_Abnormal',
      meta:{
        parentName:'orderManage',
        authority:'orderManage_Abnormal',
        hidden:false,
      },
      component:OrderManageAbnormal
    },
    {
      path:'/orderManage_Record',
      title:'减免记录',
      name:'orderManage_Record',
      meta:{
        parentName:'orderManage',
        authority:'orderManage_Record',
        hidden:false,
      },
      component:OrderManageRecord
    },
  ]
},{
  path:'/',
  name:'monthMember',
  icon:'iconfont icon-yueqiahuiyuan',
  title:'会员管理',
  meta:{
    authority:'monthMember',
    hidden:false,
  },
  component:Layout,
  children:[
    {
      path:'/monthMember_VIP',
      title:'月卡会员',
      name:'monthMember_VIP',
      meta:{
        parentName:'monthMember',
        authority:'monthMember_VIP',
        hidden:false,
      },
      component:MemberManageMonthVIP
    },{
      path:'/monthMember_Refill',
      title:'月卡续费记录',
      name:'monthMember_Refill',
      meta:{
        parentName:'monthMember',
        authority:'monthMember_Refill',
        hidden:false,
      },
      component:MemberManageRefill
    },{
      path:'/prepay_card',
      title:'储值卡会员',
      name:'prepay_card',
      meta:{
        parentName:'monthMember',
        authority:'prepay_card',
        hidden:false,
      },
      component:MemberManagePrepayCard
    },{
      path:'/prepay_card_trade',
      title:'储值卡充值记录',
      name:'prepay_card_trade',
      meta:{
        parentName:'monthMember',
        authority:'prepay_card_trade',
        hidden:false,
      },
      component:MemberManageRechargeRecord
    },{
      path:'/prepay_card_use',
      title:'储值卡使用记录',
      name:'prepay_card_use',
      meta:{
        parentName:'monthMember',
        authority:'prepay_card_use',
        hidden:false,
      },
      component:MemberManageUseRecord
    },{
      path:'/park_white_list',
      title:'白名单管理',
      name:'park_white_list',
      meta:{
        parentName:'monthMember',
        authority:'park_white_list',
        hidden:false,
      },
      component:MemberManageWhiteList
    },
  ]
},
  {
    path:'/',
    name:'vistorManage',
    icon:'iconfont icon-fangkeguanli',
    title:'访客管理',
    meta:{
      authority:'vistorManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/vistorManage_VistorMember',
        title:'访客人员管理',
        name:'vistorManage_VistorMember',
        meta:{
          parentName:'vistorManage',
          authority:'vistorManage_VistorMember',
          hidden:false,
        },
        component:VistorManage
      },
      {
        path:'/vistorManage_homeOwner',
        title:'业主管理',
        name:'vistorManage_homeOwner',
        meta:{
          parentName:'vistorManage',
          authority:'vistorManage_homeOwner',
          hidden:false,
        },
        component:OwnerManage
      },
    ]
  },
  {
    path:'/',
    name:'orderStatistics',
    icon:'iconfont icon-shujufenxi',
    title:'统计分析',
    meta:{
      authority:'orderStatistics',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/orderStatistics_CollectorReport',
        title:'收费员日报',
        name:'orderStatistics_CollectorReport',
        meta:{
          parentName:'orderStatistics',
          authority:'orderStatistics_CollectorReport',
          hidden:false,
        },
        component:OrderStatisticsTollCollector
      },
      {
        path:'/orderStatistics_DailyReport',
        title:'车场日报',
        name:'orderStatistics_DailyReport',
        meta:{
          parentName:'orderStatistics',
          authority:'orderStatistics_DailyReport',
          hidden:false,
        },
        component:OrderStatisticsDailyReport
      },
      {
        path:'/orderStatistics_MonthReport',
        title:'车场月报',
        name:'orderStatistics_MonthReport',
        meta:{
          parentName:'orderStatistics',
          authority:'orderStatistics_MonthReport',
          hidden:false,
        },
        component:OrderStatisticsMonthReport
      },
      {
        path:'/orderStatistics_Commute',
        title:'上下班记录',
        name:'orderStatistics_Commute',
        meta:{
          parentName:'orderStatistics',
          authority:'systemManage_Commute',
          hidden:false,
        },
        component:OrderStatisticsCommute
      },
    ]
  },
  {
    path:'/',
    name:'shopManage',
    icon:'iconfont icon-shanghuguanli',
    title:'商户储值',
    meta:{
      authority:'shopManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/shopManage_Shop',
        title:'商户管理',
        name:'shopManage_Shop',
        meta:{
          parentName:'shopManage',
          authority:'shopManage_Shop',
          hidden:false,
        },
        component:shopManageShop
      },
      {
        path:'/shopManage_QueryAccount',
        title:'流水查询',
        name:'shopManage_QueryAccount',
        meta:{
          parentName:'shopManage',
          authority:'shopManage_QueryAccount',
          hidden:false,
        },
        component:shopManageQueryAccount
      },
      {
        path:'/shopManage_Coupon',
        title:'优惠券管理',
        name:'shopManage_Coupon',
        meta:{
          parentName:'shopManage',
          authority:'shopManage_Coupon',
          hidden:false,
        },
        component:shopManageCoupon
      },
      {
        path:'/shopAnalysis',
        title:'商户统计',
        name:'shopAnalysis',
        meta:{
          parentName:'shopManage',
          authority:'shopAnalysis',
          hidden:false,
        },
        component:shopManageShopAnalysis
      },
    ]
  },
  {
    path:'/',
    name:'shopManageB',
    icon:'iconfont icon-shanghuguanli',
    title:'商户购买',
    meta:{
      authority:'shopManageB',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/shopManage_Shop_B',
        title:'商户管理',
        name:'shopManage_Shop_B',
        meta:{
          authority:'shopManage_Shop_B',
          hidden:false,
        },
        component:shopManageShopClassB
      },
      {
        path:'/shopManage_CouponSettings',
        title:'优惠券设置',
        name:'shopManage_CouponSettings',
        meta:{
          authority:'shopManage_CouponSettings',
          hidden:false,
        },
        component:ShopManageCouponSetClassB
      },
      {
        path:'/shopManage_QueryAccount_B',
        title:'流水查询',
        name:'shopManage_QueryAccount_B',
        meta:{
          authority:'shopManage_QueryAccount_B',
          hidden:false,
        },
        component:shopManageQueryAccountClassB
      },
      {
        path:'/shopManage_Coupon_B',
        title:'商户统计',
        name:'shopManage_Coupon_B',
        meta:{
          authority:'shopManage_Coupon_B',
          hidden:false,
        },
        component:shopManageCouponClassB
      },
    ]
  },
  {
    path:'/',
    name:'employeePermission',
    icon:'iconfont icon-yuangongguanli',
    title:'员工权限',
    meta:{
      authority:'employeePermission',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/employeePermission_Role',
        title:'角色管理',
        name:'employeePermission_Role',
        meta:{
          parentName:'employeePermission',
          authority:'employeePermission_Role',
          hidden:false,
        },
        component:ParkRoleManage
      },
      {
        path:'/employeePermission_Manage',
        title:'员工管理',
        name:'employeePermission_Manage',
        meta:{
          parentName:'employeePermission',
          authority:'employeePermission_Manage',
          hidden:false,
        },
        component:ParkEmployeeManage
      },
    ]
  },
  {
    path:'/',
    name:'valueAdded',
    icon:'el-icon-star-off',
    title:'增值服务',
    meta:{
      authority:'systemManage_AddedService',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/valueAdded_Sms',
        title:'短信服务',
        name:'valueAdded_Sms',
        meta:{
          parentName:'valueAdded',
          authority:'systemManage_AddedService_Sms',
          hidden:false,
        },
        component:ValueAddedSMS
      },
      {
        path:'/valueAdded_Screen',
        title:'数据大屏',
        name:'valueAdded_Screen',
        meta:{
          parentName:'valueAdded',
          authority:'systemManage_AddedService_Screen',
          hidden:false,
        },
        component:ValueAddedDataScreen
      },
      {
        path:'/valueAdded_Public',
        title:'商户公众号',
        name:'valueAdded_Public',
        meta:{
          parentName:'valueAdded',
          authority:'systemManage_AddServices_Public',
          hidden:false,
        },
        component:ValueAddedSubscription
      },
      {
        path:'/valueAdded_Program',
        title:'小程序收费',
        name:'valueAdded_Program',
        meta:{
          parentName:'valueAdded',
          authority:'systemManage_AddServices_Program',
          hidden:false,
        },
        component:ValueAddedApplet
      },
      {
        path:'/valueAdded_ParkPublic',
        title:'车场公众号',
        name:'valueAdded_ParkPublic',
        meta:{
          parentName:'valueAdded',
          authority:'systemManage_AddServices_ParkPublic',
          hidden:false,
        },
        component:ValueAddedParkSubscription
      },
    ]
  },
  {
    path:'/',
    name:'systemManage',
    icon:'iconfont icon-xitongguanli',
    title:'系统管理',
    meta:{
      authority:'systemManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/equipmentManage',
        title:'设备管理',
        name:'equipmentManage',
        meta:{
          parentName:'systemManage',
          authority:'equipmentManage',
          hidden:false,
        },
        component:secondLevelLayout,
        children:[
          {
            path:'/equipmentManage_Watchhouse',
            title:'岗亭管理',
            name:'equipmentManage_Watchhouse',
            meta:{
              parentName:'systemManage,equipmentManage',
              authority:'equipmentManage_Watchhouse',
              hidden:false,
            },
            component:EquipmentManageWatchhouse
          },
          {
            path:'/equipmentManage_Monitor',
            title:'监控管理',
            name:'equipmentManage_Monitor',
            meta:{
              parentName:'systemManage,equipmentManage',
              authority:'equipmentManage_Monitor',
              hidden:false,
            },
            component:EquipmentManageMonitor
          },
          {
            path:'/equipmentManage_Channel',
            title:'通道管理',
            name:'equipmentManage_Channel',
            meta:{
              parentName:'systemManage,equipmentManage',
              authority:'equipmentManage_Channel',
              hidden:false,
            },
            component:EquipmentManageChannel
          },
        ]
      },
      {
        path:'/systemManage_AdvanceSet',
        title:'高级设置',
        name:'systemManage_AdvanceSet',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_AdvanceSet',
          hidden:false,
        },
        component:SystemManageAdvanceSet
      },
      {
        path:'/systemManage_ParkPublic',
        title:'车场公众号',
        name:'systemManage_ParkPublic',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_ParkPublic',
          hidden:false,
        },
        component:SystemManageParkPublic
      },
      {
        path:'/systemManage_BlackList',
        title:'黑名单管理',
        name:'systemManage_BlackList',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_BlackList',
          hidden:false,
        },
        component:SystemManageBlackList
      },
      {
        path:'/systemManage_Account',
        title:'账户管理',
        name:'systemManage_Account',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_Account',
          hidden:false,
        },
        component:SystemManageAccount
      },
      {
        path:'/systemManage_FreeReason',
        title:'免费原因',
        name:'systemManage_FreeReason',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_FreeReason',
          hidden:false,
        },
        component:SystemManageFreeReason
      },
      {
        path:'/systemManage_CarManage',
        title:'车型管理',
        name:'systemManage_CarManage',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_CarManage',
          hidden:false,
        },
        component:secondLevelLayout,
        children:[
          {
            path:'/systemManage_CarManage_CarType',
            title:'车型设定',
            name:'systemManage_CarManage_CarType',
            meta:{
              parentName:'systemManage,systemManage_CarManage',
              authority:'systemManage_CarManage_CarType',
              hidden:false,
            },
            component:SystemManageCarType
          },
        ]
      },
      {
        path:'/systemManage_Price',
        title:'时租价格管理',
        name:'systemManage_Price',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_Price',
          hidden:false,
        },
        component:SystemManagePrice
      },
      {
        path:'/systemManage_MonthCard',
        title:'月卡套餐管理',
        name:'systemManage_MonthCard',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_MonthCard',
          hidden:false,
        },
        component:SystemManageMonthCard
      },
      {
        path:'/systemManage_Logs',
        title:'系统日志',
        name:'systemManage_Logs',
        meta:{
          parentName:'systemManage',
          authority:'systemManage_Logs',
          hidden:false,
        },
        component:SystemManageLogs
      },
      {
        target:'_blank',
        targetName:'monitorApp',
        path:'/',
        title:'中央监控',
        meta:{
          parentName:'systemManage',
          authority:'centerMonitor',
          hidden:false,
        }
      },
    ]
  },
];
