import Layout from '@/pages/layout/Layout';
import secondLevelLayout from '@/pages/layout/secondLevelLayout';

import {
  ServiceMyAccount,OperatorManage,OperatorManageStaff,
  ServiceParkManage,ServiceParkManageStaff,
  SubServiceManage,SubServiceManageStaff,
  ServiceMoneyRecord,
  ServiceNewUnionProfit,
  ServiceRoleManage,ServiceEmployeeManage,
  ServiceValueAddedSMS,ServiceValueAddedDataScreen,ServiceValueAddedSubscription,ServiceValueAddedApplet,ServiceValueAddedParkSubscription
} from 'parkingos-ui';


export const serverOtherRouter = {
  path:'/',
  name:'cityOtherRouter',
  component:Layout,
  children:[
    {
      path:'/operator_manage/operator_manage_staff',
      name:'operator_manage_staff',
      title:'运营集团员工',
      component:OperatorManageStaff
    },
    {
      path:'/server_park_manage/server_park_manage_staff',
      name:'serverParkManageStaff',
      title:'车场员工',
      component:ServiceParkManageStaff
    },
    {
      path:'/subservice_manage/subservice_manage_staff',
      name:'subServiceManageStaff',
      title:'子服务商员工',
      component:SubServiceManageStaff
    },
  ]
};

export const serverRouter = [
  {
  path:'/',
  name:'my_account',
  icon:'el-icon-news',
  title:'我的账户',
  onlyOne:true,
  meta:{
    authority:'my_account',
    hidden:false,
  },
  component:Layout,
  children:[
    {
      path:'/my_account',
      title:'我的账户',
      name:'my_account',
      meta:{
        hidden:false,
      },
      component:ServiceMyAccount
    },
  ]
},{
    path:'/',
    name:'operator_manage',
    icon:'el-icon-menu',
    title:'运营集团',
    onlyOne:true,
    meta:{
      authority:'operator_manage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/operator_manage',
        title:'运营集团管理',
        name:'operator_manage',
        meta:{
          hidden:false,
        },
        component:OperatorManage
      },
    ]
  },{
    path:'/',
    name:'server_park_manage',
    icon:'el-icon-menu',
    title:'车场管理',
    onlyOne:true,
    meta:{
      authority:'server_park_manage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/server_park_manage',
        title:'车场管理',
        name:'server_park_manage',
        meta:{
          hidden:false,
        },
        component:ServiceParkManage
      },
    ]
  },{
    path:'/',
    name:'subservice_manage',
    icon:'el-icon-menu',
    title:'子服务商管理',
    onlyOne:true,
    meta:{
      authority:'subservice_manage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/subservice_manage',
        title:'子服务商管理',
        name:'subservice_manage',
        meta:{
          hidden:false,
        },
        component:SubServiceManage
      },
    ]
  },{
    path:'/',
    name:'serverTrade',
    icon:'el-icon-document',
    title:'交易中心',
    onlyOne:true,
    meta:{
      authority:'serverTrade',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/serverTrade_MoneyRecord',
        title:'资金流水',
        name:'serverTrade_MoneyRecord',
        meta:{
          authority:'serverTrade_MoneyRecord',
          hidden:false,
        },
        component:ServiceMoneyRecord
      },
    ]
  },{
    path:'/',
    name:'serverStatistics',
    icon:'el-icon-document',
    title:'统计分析',
    onlyOne:true,
    meta:{
      authority:'serverStatistics',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/serverStatistics_NewUnionProfit',
        title:'车场分润报表',
        name:'serverStatistics_NewUnionProfit',
        meta:{
          hidden:false,
        },
        component:ServiceNewUnionProfit
      },
    ]
  },{
    path:'/',
    name:'serverResources',
    icon:'iconfont icon-yuangongguanli',
    title:'人力资源',
    meta:{
      authority:'serverResources',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/serverResources_RoleManage',
        title:'角色管理',
        name:'serverResources_RoleManage',
        meta:{
          authority:'serverResources_RoleManage',
          hidden:false,
        },
        component:ServiceRoleManage
      },{
        path:'/serverResources_EmployeeManage',
        title:'员工管理',
        name:'serverResources_EmployeeManage',
        meta:{
          authority:'serverResources_EmployeeManage',
          hidden:false,
        },
        component:ServiceEmployeeManage
      }
    ]
  },  {
    path:'/',
    name:'valueAdded',
    icon:'el-icon-star-off',
    title:'增值服务',
    meta:{
      authority:'serverValueAddedService',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/serverValueAddedService_Sms',
        title:'短信服务',
        name:'serverValueAddedService_Sms',
        meta:{
          authority:'serverValueAddedService_Sms',
          hidden:false,
        },
        component:ServiceValueAddedSMS
      },
      {
        path:'/serverValueAddedService_Screen',
        title:'数据大屏',
        name:'serverValueAddedService_Screen',
        meta:{
          authority:'serverValueAddedService_Screen',
          hidden:false,
        },
        component:ServiceValueAddedDataScreen
      },
      {
        path:'/serverValueAddedService_ShopApp',
        title:'商户公众号',
        name:'serverValueAddedService_ShopApp',
        meta:{
          authority:'serverValueAddedService_ShopApp',
          hidden:false,
        },
        component:ServiceValueAddedSubscription
      },
      {
        path:'/serverValueAddedService_Program',
        title:'小程序收费',
        name:'serverValueAddedService_Program',
        meta:{
          authority:'serverValueAddedService_Program',
          hidden:false,
        },
        component:ServiceValueAddedApplet
      },
      {
        path:'/serverValueAddedService_ParkApp',
        title:'车场公众号',
        name:'serverValueAddedService_ParkApp',
        meta:{
          authority:'serverValueAddedService_ParkApp',
          hidden:false,
        },
        component:ServiceValueAddedParkSubscription
      },
    ]
  },]
