import Layout from '@/pages/layout/Layout';

import {
  ShopAccount,FixCode,TicketManage,ShopRecharge,ShopRoleManage,ShopMember
} from 'parkingos-ui';

export const shopRouter = [
  {
    path:'/',
    name:'shop',
    icon:'iconfont icon-shanghuguanli',
    title:'商户管理',
    onlyOne:false,
    meta:{
      authority:'shop',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/shop',
        title:'商户管理',
        name:'shop',
        meta:{
          hidden:false,
        },
        component:ShopAccount
      },
    ]
  },{
    path:'/',
    name:'fixCode',
    icon:'iconfont icon-gudingmaguanli',
    title:'固定码管理',
    onlyOne:false,
    meta:{
      authority:'fixCode',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/fixCode',
        title:'固定码管理',
        name:'fixCode',
        meta:{
          hidden:false,
        },
        component:FixCode
      },
    ]
  },{
    path:'/',
    name:'ticketManage',
    icon:'iconfont icon-yongquanmingxi',
    title:'用券明细',
    onlyOne:false,
    meta:{
      authority:'ticketManage',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/ticketManage',
        title:'用券明细',
        name:'ticketManage',
        meta:{
          hidden:false,
        },
        component:TicketManage
      },
    ]
  },{
    path:'/',
    name:'shopRecharge',
    icon:'iconfont icon-chongzhimingxi1',
    title:'充值明细',
    onlyOne:false,
    meta:{
      authority:'shopRecharge',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/shopRecharge',
        title:'充值明细',
        name:'shopRecharge',
        meta:{
          hidden:false,
        },
        component:ShopRecharge
      },
    ]
  },{
    path:'/',
    name:'member',
    icon:'iconfont icon-yuangongguanli',
    title:'员工管理',
    onlyOne:false,
    meta:{
      authority:'member',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/shopRole',
        title:'角色管理',
        name:'shopRole',
        meta:{
          authority:'shopRole',
          hidden:false,
        },
        component:ShopRoleManage
      },{
        path:'/shopMember',
        title:'员工管理',
        name:'shopMember',
        meta:{
          authority:'shopMember',
          hidden:false,
        },
        component:ShopMember
      },
    ]
  },
]
