import Layout from '@/pages/layout/Layout';
import secondLevelLayout from '@/pages/layout/secondLevelLayout';
import {
  UnionDataCenter,
  BusinessOrderCars,BusinessOrderOrders,BusinessOrderDetail,BusinessOrderPoles,BusinessOrderIncome,BusinessOrderExpense,BusinessOrderReduce,
  MemberMonthVIP,MemberPrepayCardVIP,MemberBlackList,MemberWhiteList,
  StrategicAnalysisDailyParkReport,StrategicAnalysisDailyReport,StrategicAnalysisMonthReport,
  SystemSettingAccount,SystemSettingPark,SystemSettingParkStaff,SystemSettingRoleManage,SystemSettingEmployeeManage,SystemSettingLogsOperates,
  SmsService,SmsDistribution,

} from 'parkingos-ui';

export const unionOtherRouter = {
  path:'/',
  name:'unionOtherRouter',
  component:Layout,
  children:[
    {
      path:'/businessOrder_Orders/businessOrder_Details',
      name:'businessOrder_OrdersDetail',
      title:'订单详情',
      component:BusinessOrderDetail
    },
    {
      path:'/systemSetting_Park_Staff',
      name:'systemSetting_Park_Staff',
      title:'停车场员工管理',
      component:SystemSettingParkStaff
    },
    {
      path:'/unionValueAddedService_Sms/sms_distribution',
      name:'unionSmsServiceDistribution',
      title:'短信分配',
      component:SmsDistribution
    },
  ]
};

export const unionRouter = [
  {
    path:'/',
    name:'union_data_center',
    icon:'iconfont icon-shujuzhongxin',
    title:'数据中心',
    meta:{
      authority:'data_Center',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/union_data_center',
        title:'数据中心',
        name:'union_data_center',
        meta:{
          hidden:false,
        },
        component:UnionDataCenter
      },
    ]
  },{
    path:'/',
    name:'business_order',
    icon:'iconfont icon-order',
    title:'业务订单',
    meta:{
      authority:'businessOrder',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/businessOrder_Cars',
        title:'在场车辆',
        name:'businessOrder_Cars',
        meta:{
          authority:'businessOrder_Cars',
          hidden:false,
        },
        component:BusinessOrderCars
      },{
        path:'/businessOrder_Orders',
        title:'订单记录',
        name:'businessOrder_Orders',
        meta:{
          authority:'businessOrder_Orders',
          hidden:false,
        },
        component:BusinessOrderOrders
      },{
        path:'/businessOrder_Poles',
        title:'抬杆记录',
        name:'businessOrder_Poles',
        meta:{
          authority:'businessOrder_Poles',
          hidden:false,
        },
        component:BusinessOrderPoles
      },{
        path:'/businessOrder_Income',
        title:'交易记录',
        name:'businessOrder_Income',
        meta:{
          authority:'businessOrder_Income',
          hidden:false,
        },
        component:BusinessOrderIncome
      },{
        path:'/businessOrder_Expense',
        title:'支出记录',
        name:'businessOrder_Expense',
        meta:{
          authority:'businessOrder_Expense',
          hidden:false,
        },
        component:BusinessOrderExpense
      },{
        path:'/businessOrder_Reduce',
        title:'减免记录',
        name:'businessOrder_Reduce',
        meta:{
          authority:'businessOrder_Reduce',
          hidden:false,
        },
        component:BusinessOrderReduce
      },
    ]
  },{
    path:'/',
    name:'member',
    icon:'iconfont icon-yueqiahuiyuan',
    title:'会员',
    meta:{
      authority:'member',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/member_MonthVIP',
        title:'月卡会员',
        name:'member_MonthVIP',
        meta:{
          authority:'member_MonthVIP',
          hidden:false,
        },
        component:MemberMonthVIP
      },
      {
        path:'/member_PrepayCardVIP',
        title:'储值卡会员',
        name:'member_PrepayCardVIP',
        meta:{
          authority:'member_PrepayCardVIP',
          hidden:false,
        },
        component:MemberPrepayCardVIP
      },
      {
        path:'/member_BlackList',
        title:'黑名单管理',
        name:'member_BlackList',
        meta:{
          authority:'member_BlackList',
          hidden:false,
        },
        component:MemberBlackList
      },
      {
        path:'/member_WhiteList',
        title:'白名单管理',
        name:'member_WhiteList',
        meta:{
          authority:'member_WhiteList',
          hidden:false,
        },
        component:MemberWhiteList
      },
    ]
  },{
    path:'/',
    name:'strategicAnalysis',
    icon:'iconfont icon-shujufenxi',
    title:'财务报表',
    meta:{
      authority:'strategicAnalysis',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/strategicAnalysis_DailyParkReport',
        title:'车场日报统计',
        name:'strategicAnalysis_DailyParkReport',
        meta:{
          authority:'strategicAnalysis_DailyParkReport',
          hidden:false,
        },
        component:StrategicAnalysisDailyParkReport
      },
      {
        path:'/strategicAnalysis_DailyReport',
        title:'集团日报统计',
        name:'strategicAnalysis_DailyReport',
        meta:{
          authority:'strategicAnalysis_DailyReport',
          hidden:false,
        },
        component:StrategicAnalysisDailyReport
      },
      {
        path:'/strategicAnalysis_MonthReport',
        title:'集团月报统计',
        name:'strategicAnalysis_MonthReport',
        meta:{
          authority:'strategicAnalysis_MonthReport',
          hidden:false,
        },
        component:StrategicAnalysisMonthReport
      }
    ]
  },{
    path:'/',
    name:'systemSetting',
    icon:'iconfont icon-xitongguanli',
    title:'系统设置',
    meta:{
      authority:'systemSetting',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/systemSetting_Info',
        title:'企业信息',
        name:'systemSetting_Info',
        meta:{
          authority:'systemSetting_Account',
          hidden:false,
        },
        component:secondLevelLayout,
        children:[
          {
            path:'/systemSetting_Account',
            title:'账户信息',
            name:'systemSetting_Account',
            meta:{

              hidden:false,
            },
            component:SystemSettingAccount
          },
        ]
      },
      {
        path:'/systemSetting_Park',
        title:'停车场',
        name:'systemSetting_Park',
        meta:{
          authority:'systemSetting_Park',
          hidden:false,
        },
        component:SystemSettingPark
      },
      {
        path:'/systemSetting_HR',
        title:'人力资源',
        name:'systemSetting_HR',
        meta:{
          authority:'systemSetting_HR',
          hidden:false,
        },
        component:secondLevelLayout,
        children:[
          {
            path:'/systemSetting_RoleManage',
            title:'角色管理',
            name:'systemSetting_RoleManage',
            meta:{
              authority:'systemSetting_RoleManage',
              hidden:false,
            },
            component:SystemSettingRoleManage
          },
          {
            path:'/systemSetting_EmployeeManage',
            title:'员工管理',
            name:'systemSetting_EmployeeManage',
            meta:{
              authority:'systemSetting_EmployeeManage',
              hidden:false,
            },
            component:SystemSettingEmployeeManage
          },
        ]
      },{
        path:'/',
        title:'日志管理',
        name:'systemSetting_LogsOperates',
        meta:{
          authority:'systemSetting_LogsOperates',
          hidden:false,
        },
        component:secondLevelLayout,
        children:[
          {
            path:'/systemSetting_LogsOperates',
            title:'操作日志管理',
            name:'systemSetting_LogsOperates',
            meta:{

              hidden:false,
            },
            component:SystemSettingLogsOperates
          },
        ]
      },
    ]
  },{
    path:'/',
    name:'unionValueAddedService',
    icon:'el-icon-star-off',
    title:'增值服务',
    meta:{
      authority:'unionValueAddedService',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        path:'/unionValueAddedService_Sms',
        title:'短信服务',
        name:'unionValueAddedService_Sms',
        meta:{
          authority:'unionValueAddedService_Sms',
          hidden:false,
        },
        component:SmsService,

      },
    ]
  },{
    path:'/',
    name:'monitorApp',
    icon:'iconfont icon-zhongyangjiankong',
    title:'中央监控',
    meta:{
      authority:'centerMonitor',
      hidden:false,
    },
    component:Layout,
    children:[
      {
        target:'_blank',
        targetName:'monitorApp',
        path:'/',
        title:'中央监控',
        meta:{
          hidden:false,
        }
      },
    ]
  },]
